pipeline:
    name: DarkMode
    identifier: DarkMode
    projectIdentifier: GestureRecognition
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: DarkMode
              identifier: DarkMode
              description: ""
              type: FeatureFlag
              spec:
                  execution:
                      steps:
                          - step:
                                type: FlagConfiguration
                                name: DarkMode
                                identifier: DarkMode
                                spec:
                                    feature: Dark_Mode
                                    environment: Production
                                    instructions:
                                        - identifier: SetFeatureFlagStateIdentifier
                                          type: SetFeatureFlagState
                                          spec:
                                              state: "on"
                                timeout: 10m
                          - step:
                                type: ShellScript
                                name: Selenium
                                identifier: Selenium
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo "Running Selenium Tests..."
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
