apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mansong-letsencrypt-staging
  namespace: staging
spec:
  dnsNames:
    - mansong.ff-demo.co.uk
  commonName: "mansong.ff-demo.co.uk"
  secretName: mansong-staging-cert
  issuerRef:
    name: mansong-letsencrypt-staging
    kind: ClusterIssuer