apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: mansong-letsencrypt-staging
  namespace: staging
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: martin.ansong@protonmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
       ingress:
         class: nginx
