apiVersion: v1
kind: Secret
metadata:
  name: gesturerecognition-secrets
data:
  api.key: OWUwMDdmOTUtYTZhMS00ZWU5LWE1MmMtNTYxMzAyZTE4NTkw

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: gesturerecognition
    labels:
      app: gesturerecognition
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gesturerecognition
  template:
    metadata:
      labels:
        app: gesturerecognition
    spec:
      containers:
        - image: mansong/gesturerecognition:latest
          imagePullPolicy: "Always"
          name: gesturerecognition
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "2.0"
              memory: 8Gi
            requests:
              cpu: 500m
              memory: 4Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: REACT_APP_API_KEY
              value: "d3544727-c59b-4e90-8fa2-c39c926b6124"
            - name: REACT_APP_HARNESS_IDENTIFIER
              valueFrom:
                configMapKeyRef:
                  name: gesturerecognition-conf
                  key: harness.identifier
            - name: REACT_APP_HARNESS_TARGET_NAME
              valueFrom:
                configMapKeyRef:
                  name: gesturerecognition-conf
                  key: harness.target
            - name: REACT_APP_HARNESS_EMAIL_ATTR
              valueFrom:
                configMapKeyRef:
                  name: gesturerecognition-conf
                  key: harness.email_attr
            - name: REACT_APP_HARNESS_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: gesturerecognition-conf
                  key: harness.debug

---

apiVersion: v1
kind: Service
metadata:
    name: gesturerecognition-svc
spec:
  type: ClusterIP
  selector:
    app: gesturerecognition
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80