apiVersion: v1
kind: ConfigMap
metadata:
  name: gesturerecognition-conf
data:
  harness.debug: 'true'
  config.js: |
    window.REACT_APP_API_KEY='2ebbed7c-5a01-4e00-af22-f3e57cf4396c';

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: gesturerecognition
    labels:
      app: gesturerecognition
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gesturerecognition
  template:
    metadata:
      labels:
        app: gesturerecognition
    spec:
      containers:
        - image: mansong/gesturerecognition:latest
          imagePullPolicy: "Always"
          name: gesturerecognition
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1.0"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 300
          env:
            - name: REACT_APP_HARNESS_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: gesturerecognition-conf
                  key: harness.debug
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: gesturerecognition-conf

---

apiVersion: v1
kind: Service
metadata:
    name: gesturerecognition-svc
spec:
  type: ClusterIP
  selector:
    app: gesturerecognition
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
