inputSet:
  identifier: "default"
  pipeline:
    identifier: "reactjs"
    properties:
      ci:
        codebase:
          build:
            type: "branch"
            spec:
              branch: "main"
    stages:
    - stage:
        identifier: "Deploy_To_Development"
        type: "Deployment"
        spec:
          serviceConfig:
            serviceDefinition:
              type: "Kubernetes"
              spec:
                artifacts:
                  primary:
                    type: "DockerRegistry"
                    spec:
                      tagRegex: "latest"
  name: "default"
  orgIdentifier: "default"
  projectIdentifier: "mansongff"
