apiVersion: v1
kind: Secret
metadata:
  name: gesturerecognition-secrets
data:
  api.key: OWUwMDdmOTUtYTZhMS00ZWU5LWE1MmMtNTYxMzAyZTE4NTkw

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: gesturerecognition
    labels:
      app: gesturerecognition
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gesturerecognition
  template:
    metadata:
      labels:
        app: gesturerecognition
    spec:
      containers:
        - image: mansong/gesturerecognition:1.2.0
          name: gesturerecognition
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
          env:
            - name: REACT_APP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gesturerecognition-secrets
                  key: api.key
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf

---

apiVersion: v1
kind: Service
metadata:
    name: gesturerecognition-svc
spec:
  type: LoadBalancer
  selector: 
    app: gesturerecognition
  ports:
    - protocol: TCP
      port: 80